server:
    port: 8080

spring:
########################################## mysql配置 #################################################
    datasource:
        url: jdbc:mysql://localhost:3306/boot?characterEncoding=utf8&serverTimezone=PRC
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        database: mysql
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

########################################## mysql配置 #################################################